# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'face_demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for face_demo
    pod 'MBProgressHUD', '~> 1.0.0'
    pod 'AFNetworking'


end
